/**
 * @author panezhang
 * @email panezhang@yangqianguan.com
 * @date 2017-12-12 19:14:53.235
 * @desc generated by gulp
 */

export default {
    name: 'Demo',

    props: {
        id: {
            required: true
        }
    },

    asyncData: ({store, route}) => store.dispatch('fetchItem', route.params.id),

    computed: {
        nextId() {
            return +this.id + 1;
        },

        item() {
            return this.$store.state.items[this.id];
        }
    }
};
