/**
 * @author panezhang
 * @email panezhang@yangqianguan.com
 * @date 2017-12-12 19:14:53.235
 * @desc generated by gulp
 */

import demo, {A_TYPES} from 'src/app/store/module/demo';

export default {
    name: 'Demo',

    props: {
        id: {
            required: true
        }
    },

    storeModules: {demo},

    asyncData: ({store, route}) => store.dispatch(A_TYPES.FETCH_ITEM, route.params.id),

    computed: {
        nextId() {
            return +this.id + 1;
        },

        item() {
            return this.$store.state.demo.items[this.id];
        }
    }
};
